schema_version = "1.0.0"

id = "shot_matcher"
version = "3.5.4"
name = "Shot Matcher"
tagline = "Analyzes colors of an image or movie clip and applies it in the compositor"
maintainer = "Spencer Magnusson <semagnum+blenderextensions@gmail.com>"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/semagnum/shot_matcher"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Compositing"]

blender_version_min = "4.0.0"
# Optional: maximum supported Blender version, but currently no max version at the moment
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# Optional: required by some licenses.
copyright = [
  "2024 Spencer Magnusson",
]

[build]
paths_exclude_pattern = [
    ".git/",
    "venv/",
    "__pycache__/",
    "*.zip",
    ".idea/",
    ".vscode/",
    "docs/",
]